name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CONFIGURE_PRESET: windows
  BUILD_PRESET: windows-release
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset debug

    - name: Build project
      run: cmake --build build --preset debug