name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CONFIGURE_PRESET: windows
  BUILD_PRESET: windows-release
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install GTest

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build project
      run: cmake --build build --config Debug

    - name: Build Test target specifically
      run: cmake --build build --target Test --config Debug
